ALTER TABLE messages
    ADD COLUMN IF NOT EXISTS content_type TEXT NOT NULL DEFAULT 'text';

ALTER TABLE messages
    ADD COLUMN IF NOT EXISTS emoji_count INTEGER NOT NULL DEFAULT 0;

ALTER TABLE messages
    ADD COLUMN IF NOT EXISTS reaction_count INTEGER NOT NULL DEFAULT 0;
